<p align="center">
  <a href="https://imc.uc.cl" target="_blank">
    <img src="attachment:image.png" alt="IMC" width="220">
  </a>
</p>

# IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Profesor:** Rodrigo A. Carrasco <br>
---

## Tarea 04 – Aprendizaje automático

- **Fecha de Entrega:** 13 de noviembre de 2025, a las 23:59.
- **Fecha de publicación**: 30 de octubre de 2025.
- **Formato de entrega:** Notebook ejecutado y comentado (`.ipynb`) en el módulo de Tarea 04 habilitado en Canvas.

## Instrucciones

- Esta Tarea debe desarrollarse de manera totalmente *individual*, de acuerdo a lo establecido en la sección de Integridad Académica en el programa del curso.
- La Tarea debe ser desarrollada en lenguaje de programación Python y la entrega en formato Jupyter Notebook.
- El desarrollo del Notebook debe ser claro y ordenado, incluyendo anotaciones (markdown) y comentarios que permitan seguir fácilmente el código y los pasos implementados a los correctores, y siguiendo buenas prácticas de programación. La presentación y claridad del notebook y código forman parte de la evaluación de la tarea.
- Notebook **autocontenible** que:
   - Ejecute sin errores todas las celdas.
  - Contenga tanto el código como los comentarios y explicaciones necesarias.
  - Incluya visualizaciones claras y correctamente etiquetadas.
- No se aceptarán notebooks con celdas rotas o que dependan de rutas externas no indicadas en la tara.

- Deben hacer sus consultas y comentarios sobre la Tarea a traves del canal de Tareas en eo del curso en Canvas.os.
cteriza.

## 1. Objetivos

- Aplicar los conceptos iniciales de manejo de datos y análisis exploratorio vistos en clases.
- Practicar la lectura, limpieza y manipulación de datos en Python.
- Desarrollar habilidades para visualizar y describir patrones y tendencias en conjuntos de datos reales.
- Fomentar la capacidad de comunicar resultados de forma clara y fundamentada.

### 1.1 Objetivo educacional

Esta Tarea tiene como objetivo que los estudiantes desarrollen la capacidad de manejar algunas de las librerías centrales para el desarrollo de Ciencia de Datos, con foco en la lectura y exploración de datos. 

### 1.2 Pregunta de ciencia de datos

Esta tarea tendrá como objetivo crear un predictor que determine el éxito o fracaso de una expedición a distintas montañas del Himalayas según datos del montañista y de la expedición. Vamos a responder a la pregunta de qué tan bien pueden atributos como año, estación, montaña, edad del montañista, entre otros, predecir el éxito o fracaso de una expedición.

### 1.3 Recomendaciones
- Utiliza las librerías sugeridas en el notebook o justifica brevemente si incorporas otras.
- Revisa que todas las celdas se ejecuten en orden, desde el inicio, sin errores.
- Comenta tu código para explicar qué hace cada sección relevante.
- Asegúrate de que las visualizaciones sean fáciles de interpretar y tengan títulos y etiquetas adecuados.

## 2. Datos

[The Himalayan Database](https://www.himalayandatabase.com/) consiste en una colección de registros de expediciones en la cordillera del Himalaya. Esta contiene información detallada de las cimas más altas del mundo, junto con miles de expediciones realizadas desde 1905 hasta 2024 e información de cada uno de los/las montañistas que han participado en ellas. (El dataset que utilizaremos fue extraído desde: https://mavenanalytics.io/data-playground/himalayan-expeditions)

Descargue el archivo `Himalayan+Expeditions.zip` disponible en el repositorio del curso. Como puede ver, esta información está separada en varios archivos `.csv`. Deberá utilizar las herramientas aprendidas durante el curso para juntar esta información, procesarla y crear un predictor que determine el éxito de una subida.

**Recomendación**: Puede revisar el archivo `himalayan_data_dictionary.csv` para saber el significado de cada una de las columnas de la base de datos.

### 2.1 Librerías

Para esta tarea puede utilizar cualquiera de las librerías previamente utilizadas en el curso. Puede agregar otras si lo estima conveniente para el desarrollo de la Tarea.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# ...agreuge otras librerías si lo considera relevante

## 3. Carga y limpieza (1 punto)

### 3.1 DataFrame unificado (0.2 pts)

Inspeccione los atributos de cada dataset y extraiga la siguiente información de ellos:

1. Información de las montañas:
    * ID de la cima (`peakid`)
    * Nombre común de la montaña (`pkname`)
    * Altura (m) (`heightm`)
    * Cantidad de expediciones exitosas (`success_exp`)
    * Cantidad de expediciones fallidas (`failed_exp`)

2. Información de las expediciones:
    * ID de la expedición (`expid`)
    * Año (`year`)
    * Estación del año (`season`)

3. Información de los montañistas:
    * ID del miembro (`memid`)
    * Sexo (`sex`)
    * Año de nacimiento (`yob`)
    * Nacionalidad (`citizen`)
    * Completó la expedición exitosamente (`msuccess`)

Genere un único DataFrame con todos estos atributos, donde cada fila represente el ascenso de un/a montañista en una expedición. (Ojo que esto no necesariamente significa que cada fila será una persona diferente: si una persona escaló dos cumbres distintas en dos expediciones, esta debería aparecer en su DataFrame como dos filas separadas.)

In [10]:
# respuestas
df_exped = pd.read_csv("exped.csv")

# Por alguna razon el csv no esta en el predeterminado utf-8, por lotanto lo abrimos con latin1
df_refer = pd.read_csv("refer.csv", encoding="latin1")

df_peaks = pd.read_csv("peaks.csv")

df_peaks_with_exp = pd.read_csv("peaks_with_exp.csv")

df_members = pd.read_csv("members.csv")

C:\Users\crist\AppData\Local\Temp\ipykernel_29152\2760736629.py:2: DtypeWarning: Columns (8,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df_exped = pd.read_csv("exped.csv")
C:\Users\crist\AppData\Local\Temp\ipykernel_29152\2760736629.py:11: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  df_members = pd.read_csv("members.csv")

In [11]:
df_exped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11425 entries, 0 to 11424
Data columns (total 65 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   expid       11425 non-null  object
 1   peakid      11425 non-null  object
 2   year        11425 non-null  int64
 3   season      11425 non-null  object
 4   host        11425 non-null  object
 5   route1      11275 non-null  object
 6   route2      360 non-null    object
 7   route3      30 non-null     object
 8   route4      5 non-null      object
 9   nation      11425 non-null  object
 10  leaders     11401 non-null  object
 11  sponsor     10609 non-null  object
 12  success1    11425 non-null  bool
 13  success2    11425 non-null  bool
 14  success3    11425 non-null  bool
 15  success4    11425 non-null  bool
 16  ascent1     2778 non-null   object
 17  ascent2     101 non-null    object
 18  ascent3     11 non-null     object
 19  ascent4     4 non-null      object
 20  claimed     11425 non-null  bool
 21  disputed    11425 non-null  bool
 22  countries   4113 non-null   object
 23  approach    5436 non-null   object
 24  bcdate      9795 non-null   object
 25  smtdate     10670 non-null  object
 26  smttime     4982 non-null   float64
 27  smtdays     9671 non-null   float64
 28  totdays     8406 non-null   float64
 29  termdate    8450 non-null   object
 30  termreason  11425 non-null  object
 31  termnote    4648 non-null   object
 32  highpoint   11425 non-null  int64
 33  traverse    11425 non-null  bool
 34  ski         11425 non-null  bool
 35  parapente   11425 non-null  bool
 36  camps       11425 non-null  int64
 37  rope        11425 non-null  int64
 38  totmembers  11425 non-null  int64
 39  smtmembers  11425 non-null  int64
 40  mdeaths     11425 non-null  int64
 41  tothired    11425 non-null  int64
 42  smthired    11425 non-null  int64
 43  hdeaths     11425 non-null  int64
 44  nohired     11425 non-null  bool
 45  o2used      11425 non-null  bool
 46  o2none      11425 non-null  bool
 47  o2climb     11425 non-null  bool
 48  o2descent   11425 non-null  bool
 49  o2sleep     11425 non-null  bool
 50  o2medical   11425 non-null  bool
 51  o2taken     11425 non-null  bool
 52  o2unkwn     11425 non-null  bool
 53  othersmts   2199 non-null   object
 54  campsites   11046 non-null  object
 55  accidents   3001 non-null   object
 56  achievment  976 non-null    object
 57  agency      9696 non-null   object
 58  comrte      11425 non-null  bool
 59  stdrte      11425 non-null  bool
 60  primrte     11425 non-null  bool
 61  primmem     11425 non-null  bool
 62  primref     11425 non-null  bool
 63  primid      753 non-null    object
 64  chksum      11425 non-null  int64
dtypes: bool(23), float64(3), int64(11), object(28)
memory usage: 3.9+ MB

In [12]:
df_refer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15586 entries, 0 to 15585
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   expid       15586 non-null  object
 1   refid       15586 non-null  int64
 2   ryear       15586 non-null  int64
 3   rtype       15583 non-null  object
 4   rjrnl       7218 non-null   object
 5   rauthor     5283 non-null   object
 6   rtitle      10065 non-null  object
 7   rpublisher  1130 non-null   object
 8   rpubdate    8306 non-null   float64
 9   rlanguage   2352 non-null   object
 10  rcitation   7234 non-null   object
 11  ryak94      631 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 1.4+ MB

In [13]:
df_peaks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   peakid      480 non-null    object
 1   pkname      480 non-null    object
 2   pkname2     257 non-null    object
 3   location    479 non-null    object
 4   heightm     480 non-null    int64
 5   heightf     480 non-null    int64
 6   himal       480 non-null    object
 7   region      480 non-null    object
 8   open        480 non-null    bool
 9   unlisted    480 non-null    bool
 10  trekking    480 non-null    bool
 11  trekyear    29 non-null     float64
 12  restrict    275 non-null    object
 13  phost       480 non-null    object
 14  pstatus     480 non-null    object
 15  pyear       362 non-null    float64
 16  pseason     363 non-null    object
 17  pmonth      357 non-null    object
 18  pday        340 non-null    float64
 19  pexpid      360 non-null    object
 20  pcountry    362 non-null    object
 21  psummiters  477 non-null    object
 22  psmtnote    76 non-null     object
dtypes: bool(3), float64(3), int64(2), object(15)
memory usage: 76.5+ KB

In [14]:
df_peaks_with_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peakid       480 non-null    object
 1   pkname       480 non-null    object
 2   pkname2      257 non-null    object
 3   location     479 non-null    object
 4   heightm      480 non-null    int64
 5   heightf      480 non-null    int64
 6   himal        480 non-null    object
 7   region       480 non-null    object
 8   open         480 non-null    bool
 9   unlisted     480 non-null    bool
 10  trekking     480 non-null    bool
 11  trekyear     29 non-null     float64
 12  restrict     275 non-null    object
 13  phost        480 non-null    object
 14  pstatus      480 non-null    object
 15  pyear        362 non-null    float64
 16  pseason      363 non-null    object
 17  pmonth       357 non-null    object
 18  pday         340 non-null    float64
 19  pexpid       360 non-null    object
 20  pcountry     362 non-null    object
 21  psummiters   477 non-null    object
 22  psmtnote     76 non-null     object
 23  failed_exp   480 non-null    int64
 24  success_exp  480 non-null    int64
dtypes: bool(3), float64(3), int64(4), object(15)
memory usage: 84.0+ KB

In [15]:
df_members.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89000 entries, 0 to 88999
Data columns (total 61 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   expid       89000 non-null  object
 1   membid      89000 non-null  int64
 2   peakid      89000 non-null  object
 3   myear       89000 non-null  int64
 4   mseason     89000 non-null  object
 5   fname       88897 non-null  object
 6   lname       87876 non-null  object
 7   sex         89000 non-null  object
 8   yob         83592 non-null  float64
 9   citizen     88993 non-null  object
 10  status      89000 non-null  object
 11  residence   80170 non-null  object
 12  occupation  58261 non-null  object
 13  leader      89000 non-null  bool
 14  deputy      89000 non-null  bool
 15  bconly      89000 non-null  bool
 16  nottobc     89000 non-null  bool
 17  support     89000 non-null  bool
 18  disabled    89000 non-null  bool
 19  hired       89000 non-null  bool
 20  sherpa      89000 non-null  bool
 21  tibetan     89000 non-null  bool
 22  msuccess    89000 non-null  bool
 23  mclaimed    89000 non-null  bool
 24  mdisputed   89000 non-null  bool
 25  msolo       89000 non-null  bool
 26  mtraverse   89000 non-null  bool
 27  mski        89000 non-null  bool
 28  mparapente  89000 non-null  bool
 29  mspeed      89000 non-null  bool
 30  mhighpt     89000 non-null  bool
 31  mperhighpt  64054 non-null  float64
 32  msmtdate1   59731 non-null  object
 33  msmtdate2   449 non-null    object
 34  msmtdate3   22 non-null     object
 35  msmttime1   26512 non-null  float64
 36  msmttime2   244 non-null    float64
 37  msmttime3   7 non-null      float64
 38  mroute1     89000 non-null  int64
 39  mroute2     89000 non-null  int64
 40  mroute3     89000 non-null  int64
 41  mascent1    89000 non-null  int64
 42  mascent2    89000 non-null  int64
 43  mascent3    89000 non-null  int64
 44  mo2used     89000 non-null  bool
 45  mo2none     89000 non-null  bool
 46  mo2climb    89000 non-null  bool
 47  mo2descent  89000 non-null  bool
 48  mo2sleep    89000 non-null  bool
 49  mo2medical  89000 non-null  bool
 50  mo2note     15347 non-null  object
 51  death       89000 non-null  bool
 52  deathdate   1132 non-null   object
 53  deathtime   568 non-null    float64
 54  deathtype   1158 non-null   object
 55  deathhgtm   89000 non-null  int64
 56  deathclass  1158 non-null   object
 57  msmtbid     89000 non-null  object
 58  msmtterm    88824 non-null  object
 59  hcn         295 non-null    float64
 60  mchksum     89000 non-null  int64
dtypes: bool(25), float64(7), int64(10), object(19)
memory usage: 26.6+ MB

In [ ]:
# Información de las montanas
df_info_montanas = df_peaks_with_exp[['peakid', 'pkname', 'heightm', 'success_exp', 'failed_exp']]
df_info_montanas.head()

  peakid         pkname  heightm  success_exp  failed_exp
0   ACHN         Aichyn     6055            2           1
1   AMAD     Ama Dablam     6814         1123         453
2   AMOT       Amotsang     6393            1           2
3   AMPG  Amphu Gyabjen     5630            3           1
4   AMPH        Amphu I     6740            1           1

In [28]:
df_info_montanas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480 entries, 0 to 479
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peakid       480 non-null    object
 1   pkname       480 non-null    object
 2   heightm      480 non-null    int64
 3   success_exp  480 non-null    int64
 4   failed_exp   480 non-null    int64
dtypes: int64(3), object(2)
memory usage: 18.9+ KB

In [35]:
# Informacion de las expediciones (se le suma peakid para unir con montanas)
df_info_exp = df_exped[['expid', 'year', 'season', 'peakid']]
df_info_exp.head()

       expid  year  season peakid
0  ANN260101  1960  Spring   ANN2
1  ANN269301  1969  Autumn   ANN2
2  ANN273101  1973  Spring   ANN2
3  ANN278301  1978  Autumn   ANN2
4  ANN279301  1979  Autumn   ANN2

In [36]:
df_info_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11425 entries, 0 to 11424
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   expid   11425 non-null  object
 1   year    11425 non-null  int64
 2   season  11425 non-null  object
 3   peakid  11425 non-null  object
dtypes: int64(1), object(3)
memory usage: 357.2+ KB

In [37]:
# Como season esta como objeto y solo hay 4 opciones, la transformamos a category
df_info_exp['season'] = df_info_exp['season'].astype('category')
df_info_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11425 entries, 0 to 11424
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   expid   11425 non-null  object
 1   year    11425 non-null  int64
 2   season  11425 non-null  category
 3   peakid  11425 non-null  object
dtypes: category(1), int64(1), object(2)
memory usage: 279.3+ KB

C:\Users\crist\AppData\Local\Temp\ipykernel_29152\3120423010.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info_exp['season'] = df_info_exp['season'].astype('category')

In [38]:
# Informacion monatnistas (se le suma expid para unir con expediciones)
df_info_montanistas = df_members[['membid', 'sex', 'yob', 'citizen', 'msuccess', 'expid']]
df_info_montanistas.head()

   membid sex     yob    citizen  msuccess      expid
0       2   M  1972.0  Australia     False  AMAD01101
1       1   M  1968.0  Australia     False  AMAD01101
2       3   M  1960.0  Australia     False  AMAD01101
3       4   M  1966.0  Australia     False  AMAD01101
4       5   F  1970.0  Australia     False  AMAD01101

In [39]:
df_info_montanistas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89000 entries, 0 to 88999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   membid    89000 non-null  int64
 1   sex       89000 non-null  object
 2   yob       83592 non-null  float64
 3   citizen   88993 non-null  object
 4   msuccess  89000 non-null  bool
 5   expid     89000 non-null  object
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 3.5+ MB

In [40]:
df_info_montanistas['sex'] = df_info_montanistas['sex'].astype('category')
# La columna de sexo se cambio a category por tener dos opciones
df_info_montanistas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89000 entries, 0 to 88999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   membid    89000 non-null  int64
 1   sex       89000 non-null  category
 2   yob       83592 non-null  float64
 3   citizen   88993 non-null  object
 4   msuccess  89000 non-null  bool
 5   expid     89000 non-null  object
dtypes: bool(1), category(1), float64(1), int64(1), object(2)
memory usage: 2.9+ MB

C:\Users\crist\AppData\Local\Temp\ipykernel_29152\3395039316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info_montanistas['sex'] = df_info_montanistas['sex'].astype('category')

In [42]:
df_unido = pd.merge(df_info_exp, df_info_montanas, on='peakid', how='outer')
df_unido = pd.merge(df_unido, df_info_montanistas, on='expid', how='outer')
df_unido.head()

,expid,year,season,peakid,pkname,heightm,success_exp,failed_exp,membid,sex,yob,citizen,msuccess
0,ACHN15301,2015.0,Autumn,ACHN,Aichyn,6055,2,1,1.0,M,1992.0,Japan,True
1,ACHN15301,2015.0,Autumn,ACHN,Aichyn,6055,2,1,2.0,F,1992.0,Japan,True
2,ACHN15301,2015.0,Autumn,ACHN,Aichyn,6055,2,1,4.0,M,1990.0,Japan,True
3,ACHN15301,2015.0,Autumn,ACHN,Aichyn,6055,2,1,5.0,M,1993.0,Japan,True
4,ACHN15301,2015.0,Autumn,ACHN,Aichyn,6055,2,1,3.0,M,1995.0,Japan,True

In [43]:
df_unido.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89168 entries, 0 to 89167
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   expid        89104 non-null  object
 1   year         89104 non-null  float64
 2   season       89104 non-null  category
 3   peakid       89168 non-null  object
 4   pkname       89168 non-null  object
 5   heightm      89168 non-null  int64
 6   success_exp  89168 non-null  int64
 7   failed_exp   89168 non-null  int64
 8   membid       89089 non-null  float64
 9   sex          89089 non-null  category
 10  yob          83665 non-null  float64
 11  citizen      89082 non-null  object
 12  msuccess     89089 non-null  object
dtypes: category(2), float64(3), int64(3), object(5)
memory usage: 7.7+ MB

### 3.2 Limpieza y transformación (0.2 pts)

Inspeccione y procese su DataFrame para generar uno nuevo llamado `clean_df`. En esta sección usted debe decidir si es necesario:

* Limpiar valores nulos, duplicados o inválidos.
* Imputar valores.
* Transformar tipos de columnas.

Justifique su procesamiento.

In [ ]:
# respuestas

### 3.2 Creación de nuevas columnas (0.6 pts)

Vamos a crear un par de columnas nuevas que nos ayudarán a hacer una análisis exploratorio del dataset.
Utilizando las columnas actuales, genere y agregue las siguientes columnas a su DataFrame:

* `age`: Edad del montañista a la fecha de la expedición.
* `peak_success_p`: Porcentaje de expediciones exitosas de la cima respectiva.

De ser necesario, aplique procesos de limpieza y transformación a estas columnas también (asegúrese de que todos los valores sean coherentes).

In [ ]:
# respuestas

## 4. EDA (2.5 puntos)

Con el dataset obtenido, responda las siguientes preguntas. Para cada una de ellas, realice al menos un gráfico que permita visualizar el comportamiento de su dataset.

a. **(0.5 pts)** ¿Cuántos ascensos exitosos y fallidos hay en su dataset? ¿A qué porcentaje del total corresponde cada categoría?

b. **(0.5 pts)** ¿Cómo se distribuyen las edades de los/las montañistas en la base de datos?

c. **(0.5 pts)** ¿Cómo se distribuye la cantidad de ascensos según estación del año? ¿Cuál es el porcentaje de éxito por estación? Muestre la cantidad de filas de ascensos exitosas y fallidas para cada estación.

d. **(0.5 pts)** ¿Cómo cambia la cantidad de ascensos en el tiempo? Muestre la cantidad de ascensos exitosos y fallidos por año.

e. **(0.5 pts)** ¿Existe una correlación entre el porcentaje de éxito de ascenso y la altura de una cumbre? Haga un scatterplot para todas las cumbres que hayan sido escaladas por al menos 10 expediciones en total (tanto fallidas como exitosas).

In [ ]:
# respuestas

Respuestas:

## 5. Predictor (2.5 puntos)

Ahora veremos si la información que tenemos nos permite predecir el éxito de un ascenso por alguna persona en particular. Primero, defina su **X** (matriz de atributos) e **y** (etiqueta a predecir) de la siguiente manera:

* **X**: `age`, `sex`, `citizen`, `season`, `heightm`, `year`, `success_exp`, `failed_exp`
* **y**: `msuccess`

Luego, realice los pasos a continuación:

**5.1 Codificación y normalización (1 pto)**
* Codifique todas las columnas categóricas, de manera que su matriz **X** solo tenga valores numéricos.
* Divida sus datos en sets de entrenamiento y testeo. Use una división de 70-30.
* Normalice sus matrices de atributos. Justifique su método de normalización.

**5.2 Creación y entrenamiento de modelos (1 pto)**
* Cree y entrene los siguientes modelos:
    * Un clasificador KNN
    * Un árbol de decisión
    * Un clasificador de regresión logística
    * Un clasificador random forest **(Opcional)**

    Explique qué hiperparámetros utilizó para la creación de cada uno de ellos y qué valores le asignó.

* Finalmente, evalúe todos sus modelos con el set de testeo. Para cada uno, muestre
    * Accuracy
    * Precisión
    * Recall
    * Matriz de confusión

**5.3 Análisis de resultados (0.5 pts)**

Interprete, analice y comente sus resultados. 
* ¿Qué tendencias puede observar? ¿Se diferencian de alguna forma las predicciones entre un modelo y otro? 
* ¿Fue posible construir un predictor efectivo? Justique.

In [ ]:
# respuestas

Respuestas: